defaults: &defaults
  word:
    answers_per_word: 4
    level:
      - 1
      - 2
      - 3
  all_words: "all_words"
  option:
    - all_words
    - learned
    - not_learn
  pagination:
    categories_per_page: 10
    words_per_page: 120
    activities_per_page: 15
  lesson:
    words_per_lesson: 5
    time_in_minutes: 2
  activity:
    follow: "follow"
    unfollow: "unfollow"
    learned: "learned"
    learning: "learning"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
